apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob1
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: timer-container
            image: busybox
            args:
            - "bin/sh"
            - "-c"
            - "date; echo 'This is just a test job'" 
          restartPolicy: OnFailure

