apiVersion: batch/v1
kind: Job
metadata:
  name: display-numbers-job
spec:
  template:
    metadata:
      name: display-numbers
    spec:
      containers:
      - name: display-numbers-container
        image: centos:7
        command:
         - "bin/bash"
         - "-c"
         - "for i in 10 9 8 7 6 5 4 3 2 1; do sleep 2; echo $i ; done"
      restartPolicy: Never

